import type { TrackPreview } from "@/types/game";

export type SingAlongPuzzle = {
  gameId: "sing-along";
  gameVersion: "v2";
  id: string;
  date: string;
  dateKey: string;
  masterSeed: string;
  gameSeed: number;
  seed: number;
  title: string;
  songTitle: string;
  artist: string;
  previewUrl: string;
  chartDate: string;
  chartYear: number;
  chartPosition: number;
  track: TrackPreview;
  playbackStart: number;
  playbackStop: number;
  stopTimestamp: number;
  chorusTimestamp: number;
  cueDescription: string;
  setupLyricExcerpt: string;
  answerLyricExcerpt: string;
  answerLyricStartTimeSeconds: number;
  lyricExcerpt: string;
  lyricStartTimeSeconds: number;
  clipStartTimeSeconds: number;
  clipEndTimeSeconds: number;
  acceptedLyric: string;
  alternateAcceptedLyrics: string[];
  correctChoiceId: "a" | "b" | "c" | "d";
  choices: Array<{ id: "a" | "b" | "c" | "d"; text: string; isCorrect: boolean }>;
  sourceNote: string;
  deterministicSelectors: Record<string, string>;
  promptConstraints: string;
  validation: { valid: boolean; errors: string[] };
  repeatStatus: {
    checked: boolean;
    passed?: boolean;
    duplicateDetected?: boolean;
    retryCount: number;
    provider: string;
    warning?: string;
  };
  uniqueContentKey: string;
  secondaryKeys: string[];
  musicUsedContentKey: string;
  duplicateCheck: {
    duplicateDetected: boolean;
    passed: boolean;
    regenerationCount: number;
    retryCount: number;
    exhaustedCandidatePool: boolean;
    checkedAgainstCount: number;
    recentlyUsedKeys: string[];
    warning?: string;
  };
  generatedAt: string;
  contentHash: string;
  contentUniverse?: Record<string, unknown>;
};

export type SingAlongState = {
  dateKey: string;
  puzzle: SingAlongPuzzle;
  selectedChoiceId: string;
  score: number;
  label: string;
  completed: boolean;
  correct: boolean;
};
